name: Generate Superhuman Configs

on:
  schedule:
    - cron: '0 */12 * * *' # هر ۱۲ ساعت یکبار اجرا می‌شود
  workflow_dispatch: # قابلیت اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install qrcode[pil]

      - name: Run Generator Script
        run: python generate_singbox_trojan.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update Configs: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || exit 0
          git push
